apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello
  description: hello
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: test
  lifecycle: experimental
